ID_EVENT_NARRATION_0    = 0x271a
PATH_BG_NARRATION_0     = "map/main0.bgx"
PATH_ANI_NARRATION_0    = "lukeletter/?/op_message.spr"
COUNT_ANI_NARRATION_0   = 0x3
SLIDES_ANI_NARRATION_0  = [(0,3)]
ID_STREAM_NARRATION_0   = 0x1

ID_EVENT_NARRATION_1    = ID_EVENT_NARRATION_0 + 0x14
PATH_BG_NARRATION_1     = "lukeletter/luke_letter.bgx"
PATH_ANI_NARRATION_1    = "lukeletter/?/message.spr"
COUNT_ANI_NARRATION_1   = 0x4
SLIDES_ANI_NARRATION_1  = [(0,2), (2,4)]
ID_STREAM_NARRATION_0   = 0xb

ID_EVENT_NARRATION_2    = 0x3386
PATH_BG_NARRATION_2     = "map/main0.bgx"
PATH_ANI_NARRATION_2    = "lukeletter/?/message2.spr"
COUNT_ANI_NARRATION_2   = 0x6
SLIDES_ANI_NARRATION_2  = [(0,3), (3,6)]
ID_STREAM_NARRATION_0   = 0x9c

ID_EVENT_NARRATION_3    = ID_EVENT_NARRATION_2 + 4000
PATH_BG_NARRATION_3     = "map/main0.bgx"
PATH_ANI_NARRATION_3    = "lukeletter/?/end_message.spr"
COUNT_ANI_NARRATION_3   = 0x4
SLIDES_ANI_NARRATION_3  = [(0,1), (1,2), (2,4)]
ID_STREAM_NARRATION_3   = 0x152

ANI_POS_VAR             = "pos%d"