from .dramaevent import EventPlayer
from .room import RoomPlayer
from .narration import NarrationPlayer
from .endpuzzle import EndPuzzlePlayer
from .puzzle import PuzzlePlayer
from .eventtea import EventTeaPlayer
from .title import TitlePlayer
from .name import NamePlayer
from .movie import MoviePlayer
from .startpuzzle import StartPuzzlePlayer
from .staypuzzle import StayPuzzlePlayer
from .nazoba import NazobaPlayer
from .bag import BagPlayer
from .memo import MemoPlayer
from .mystery import MysteryPlayer
from .jiten import JitenPlayer
from .wfcSetup import NintendoWfcBypassPlayer
from .secret import WiFiSecretMenuPlayer, SecretMenuPlayer, TopSecretMenuPlayer, ArtModePlayer, PasscodePlayer, MovieViewModePlayer, ChrViewModePlayer
from .wiFiDownloadPuzzle import WiFiDownloadPuzzleBypassPlayer
from .codeinput import CodeInputPlayer
from .diary import DiaryPlayer