PATH_BG_MAIN                = "menu/bag/%s/diary_bg.bgx"
PATH_BG_SUB_INIT            = "menu/bag/%s/diary_sub2.bgx"
PATH_BG_SUB                 = "menu/bag/diary_sub.bgx"

PATH_ANIM_BTN_ENTRY         = "menu/bag/diary_icon.spr"
PATH_ANIM_BTN_CANCEL        = "menu/secret/%s/secret_modoru.spr"

VAR_POS_CANCEL              = "pos_o"
NAME_ANIM_CANCEL_OFF        = "click"
NAME_ANIM_CANCEL_ON         = "on"

NAME_ANIM_ENTRY_OPENED      = "pressed3"
NAME_ANIM_ENTRY_UNOPENED    = "pressed2"
NAME_ANIM_ENTRY_DISABLED    = "gfx1"
NAME_ANIM_ENTRY_LOCKED      = "gfx2"
NAME_ANIM_ENTRY_WAIT_SELECT = "gfx3"
NAME_ANIM_ENTRY_SELECTED    = "gfx4"
NAME_ANIM_ENTRY_BREAK_LOCK  = "gfx5"

PATH_TXT_DIARY              = "diary_%i.txt"

COUNT_DIARY_ENTRIES         = 12
COUNT_ENTRIES_PER_ROW       = 4

# Don't ask me why the game makes this so complicated... duplicate sprites
NAME_ANIM_BTN_OLD_OFF           = NAME_ANIM_ENTRY_WAIT_SELECT
NAME_ANIM_BTN_OLD_ON            = NAME_ANIM_ENTRY_OPENED
NAME_ANIM_BTN_OLD_CLICK         = NAME_ANIM_ENTRY_WAIT_SELECT

NAME_ANIM_BTN_NEW_OFF           = NAME_ANIM_ENTRY_LOCKED
NAME_ANIM_BTN_NEW_ON            = NAME_ANIM_ENTRY_UNOPENED
NAME_ANIM_BTN_NEW_CLICK         = NAME_ANIM_ENTRY_BREAK_LOCK

NAME_ANIM_BTN_DISABLE_OFF       = NAME_ANIM_ENTRY_DISABLED
NAME_ANIM_BTN_DISABLE_ON        = NAME_ANIM_ENTRY_DISABLED
NAME_ANIM_BTN_DISABLE_CLICK     = NAME_ANIM_ENTRY_DISABLED

NAME_ANIM_BTN_SELECTED_OFF      = NAME_ANIM_ENTRY_SELECTED
NAME_ANIM_BTN_SELECTED_ON       = NAME_ANIM_ENTRY_SELECTED
NAME_ANIM_BTN_SELECTED_CLICK    = NAME_ANIM_ENTRY_SELECTED

NAME_ANIM_BTN_DESELECTED_OFF    = NAME_ANIM_ENTRY_WAIT_SELECT
NAME_ANIM_BTN_DESELECTED_ON     = NAME_ANIM_ENTRY_OPENED
NAME_ANIM_BTN_DESELECTED_CLICK  = NAME_ANIM_ENTRY_SELECTED

POS_ENTRY_CORNER = (6,0xc)
STRIDE_X = 0x3e
STRIDE_Y = 0x36