NAME_POS_VARIABLE = "pos"
NAME_AUTO_ANIM    = "gfx"

POS_TEXT_SAVE_Y         = 76
POS_TEXT_ITEM_ADD_Y     = 0x66
POS_TEXT_SUB_GAME_ADD_Y = 0x5c
POS_TEXT_STOCK_SCREEN_Y = 100

POS_PHOTO_PIECE_TEXT    = (0x80, 100)
POS_HAMSTER_TEXT        = (0x80, 0x5c)
POS_NAZOBA_TEXT         = (0x19, 0x11)
POS_RETURN_STATION_TEXT = (0x80,0x4c)

POS_STOCK_SCREEN_NAZO_ICON  = (0x74, 0x3c)
POS_PARTY_SCREEN_NAZO_ICON  = (0x74, 0x38)
POS_LOST_SCREEN_PIECE_ICON  = (0, 0x38)
POS_PHOTO_PIECE_PIECE_ICON  = (0x74, 0x3a)

ID_CAM_PART_FOUND       = 0xc9
ID_HERB_ELEMENT_FOUND   = 0xca
ID_HAM_ELEMENT_FOUND    = 0xcb
ID_STOCK_SCREEN         = 0xcc
ID_ITEM_ADD             = 0xcd
ID_SUB_GAME_1           = 0xce
ID_SAVE_NOT_COMPLETE    = 0xd0
ID_SAVE_COMPLETE        = 0xd1
ID_SUB_GAME_0           = 0xd2
ID_SUB_GAME_2           = 0xd3
ID_PHOTO_NEW_FOUND      = 0xd4
ID_NAMING_HAM           = 0xd7
ID_LOST_SCREEN          = 0xd8
ID_FLORA_JOIN_PARTY     = 0xd9
ID_FLORA_LEAVE_PARTY    = 0xda
ID_SUB_GAME_3           = 0xdb
ID_DIARY_ELEMENT_FOUND  = 0xdc
ID_STATION_RETURN       = 0xdd
ID_PHOTO_ALL_FOUND      = 0xde
ID_UNLOCK_END_CHALLENGE = 0x4b0
ID_PHOTO_NEARLY_FOUND   = 0x640

PATH_ANIM_NAZO_ICON     = "event/nazo_icon.spr"
PATH_ANIM_PARTY         = "map/map_icons.spr"

PATH_ANIM_BUTTON_YES    = "system/btn/%s/yes.spr"
PATH_ANIM_BUTTON_NO     = "system/btn/%s/no.spr"

PATH_BG_NAZOBA_MAIN     = "event/nazobamemo_bg.bgx"
PATH_BG_NAZOBA_SUB      = "event/?/nazobamemo_sub.bgx"

COUNT_NAZOBA_PER_PAGE   = 8

ANIM_NAME_TEA = "s%d"

TEXT_INVALID_PART = "cam_%i:NO DATA"
TEXT_INVALID_HERB = "herb_%i:NO DATA"
TEXT_INVALID_HAM  = "ham_%i:NO DATA"

STRIDE_NAZOBA_TEXT      = 0x16